#!/bin/sh

#General

#Cancel .pbs job
qdel [Job number]
#Storage usage
du -c
du -cs <directory>
#Modules
module load <name>
module list 
module help <name>
module spider <name>

#OSC

#For John’s RUs
PBS -A PAA0003 
#interactive node 
qsub -IVl walltime=24:00:00 -l nodes=1:ppn=1 -A PAA0003

#DIRECTORIES
#Me: osu6658@glenn.osc.edu
#Class: osu6950
#John: /nfs/13/osu4382
#Ryan /nfs/03/osu5293
#Xing  /nfs/    /osu6696		


